### ISSUE TITLE
error reading 2802 byte TOC targz

### ISSUE THREAD

**Issue by strigazi** [giuseppe/crfs-plugin#1]
Thanks for this plugin!

I gave it a go, but when creating the overlay, I'm getting:
```
[root@strigazi-podman-crfs-001 ~]# export DATA=$(echo -n docker://gitlab-registry.cern.ch/strigazi/containers/busybox:1.31-stargz | base64 -w0)
[root@strigazi-podman-crfs-001 ~]# fuse-overlayfs -d -o fast_ino=1,plugins=/usr/local/libexec/crfs-plugin.so,lowerdir=//crfs/$DATA/$(pwd)/lower,upperdir=upper,workdir=workdir merged
cannot open stargz file [100 111 99 107 101 114 58 47 47 103 105 116 108 97 98 45 114 101 103 105 115 116 114 121 46 99 101 114 110 46 99 104 47 115 116 114 105 103 97 122 105 47 99 111 110 116 97 105 110 101 114 115 47 98 117 115 121 98 111 120 58 49 46 51 49 45 115 116 97 114 103 122]: error reading 2802 byte TOC targz: Invalid status code returned when fetching blob 400 (Bad Request)

```

The image is publicly accessible. Any hints?

**Comment by strigazi** [comment]
The same image from docker.io works fine. Any pointer where I should look to make it work with the gitlab registry? Is this some kind of validation on the layer?

```
docker.io/strigazi/busybox                            1.31-stargz         ad875e61b216        16 hours ago        1.28 MB
gitlab-registry.cern.ch/strigazi/containers/busybox   1.31-stargz         ad875e61b216        16 hours ago        1.28 MB
```

**Comment by giuseppe** [comment]
it looks like the registry doesn't support (or accept) HTTP range requests.

**Comment by strigazi** [comment]
Right, this issue [0] mentions artifacts, but it should be the same implementation.

I'll check if this requirement comes from crfs or the plug-in and I will close the issue.

Thanks!

[0] https://gitlab.com/gitlab-com/support-forum/issues/3655

**Comment by strigazi** [comment]
It is pretty clear from crfs' Readme
https://github.com/google/crfs/blob/12599487789fa1d5abead897932c40a1a17929dd/README.md#operation

Thanks again Giuseppe!

**Comment by giuseppe** [comment]
@strigazi had a chance to play with it?  Have you had other problems using it?

**Comment by strigazi** [comment]
Hello @giuseppe , 

I just did two small examples. I'll test more. We are also adding our plugin, we should have something tomorrow. I'll let you know.

Cheers!
